const { join } = require('path');
const { createConfig } = require('@rollup-umd/documentation');
const { name } = require('./package.json');
const config = createConfig({
  moduleAliases: {
    $PACKAGE_NAME: join(__dirname),
    [name]: join(__dirname),
  },
  styleguideComponents: {
    // components
    StyleGuide: join(__dirname, 'src/StyleGuide'),
    StyleGuideRenderer: join(__dirname, 'src/StyleGuide/StyleGuideRenderer'),
    Wrapper: join(__dirname, 'src/Wrapper'),
    // rsg-bs-components
    ArgumentRenderer: join(__dirname, 'src/Argument/ArgumentRenderer.js'),
    ArgumentsRenderer: join(__dirname, 'src/Arguments/ArgumentsRenderer.js'),
    CodeRenderer: join(__dirname, 'src/Code/CodeRenderer.js'),
    Components: join(__dirname, 'src/Components'),
    ComponentsRenderer: join(__dirname, 'src/Components/ComponentsRenderer.js'),
    ComponentsList: join(__dirname, 'src/ComponentsList/ComponentsList.js'),
    ComponentsListRenderer: join(__dirname, 'src/ComponentsList/ComponentsListRenderer.js'),
    Editor: join(__dirname, 'src/Editor/Editor.js'),
    ErrorRenderer: join(__dirname, 'src/Error/ErrorRenderer.js'),
    ExamplePlaceholderRenderer: join(__dirname, 'src/ExamplePlaceholder/ExamplePlaceholderRenderer.js'),
    Examples: join(__dirname, 'src/Examples'),
    ExamplesRenderer: join(__dirname, 'src/Examples/ExamplesRenderer.js'),
    HeadingRenderer: join(__dirname, 'src/Heading/HeadingRenderer.js'),
    LinkRenderer: join(__dirname, 'src/Link/LinkRenderer.js'),
    LogoRenderer: join(__dirname, 'src/Logo/LogoRenderer.js'),
    Markdown: join(__dirname, 'src/Markdown'),
    Blockquote: join(__dirname, 'src/Markdown/Blockquote'),
    BlockquoteRenderer: join(__dirname, 'src/Markdown/Blockquote/BlockquoteRenderer.js'),
    Checkbox: join(__dirname, 'src/Markdown/Checkbox'),
    CheckboxRenderer: join(__dirname, 'src/Markdown/Checkbox/CheckboxRenderer.js'),
    Hr: join(__dirname, 'src/Markdown/Hr'),
    HrRenderer: join(__dirname, 'src/Markdown/Hr/HrRenderer.js'),
    JsDoc: join(__dirname, 'src/JsDoc'),
    List: join(__dirname, 'src/Markdown/List'),
    ListRenderer: join(__dirname, 'src/Markdown/List/ListRenderer.js'),
    MarkdownHeading: join(__dirname, 'src/Markdown/MarkdownHeading'),
    MarkdownHeadingRenderer: join(__dirname, 'src/Markdown/MarkdownHeading/MarkdownHeadingRenderer.js'),
    Pre: join(__dirname, 'src/Markdown/Pre'),
    PreRenderer: join(__dirname, 'src/Markdown/Pre/PreRenderer.js'),
    TableHeadRenderer: join(__dirname, 'src/Markdown/Table/TableHeadRenderer.js'),
    TableBodyRenderer: join(__dirname, 'src/Markdown/Table/TableBodyRenderer.js'),
    TableRowRenderer: join(__dirname, 'src/Markdown/Table/TableRowRenderer.js'),
    TableCellRenderer: join(__dirname, 'src/Markdown/Table/TableCellRenderer.js'),
    MessageRenderer: join(__dirname, 'src/Message/MessageRenderer.js'),
    MethodsRenderer: join(__dirname, 'src/Methods/MethodsRenderer.js'),
    NameRenderer: join(__dirname, 'src/Name/NameRenderer.js'),
    ParaRenderer: join(__dirname, 'src/Para/ParaRenderer.js'),
    PathlineRenderer: join(__dirname, 'src/Pathline/PathlineRenderer.js'),
    Playground: join(__dirname, 'src/Playground'),
    PlaygroundRenderer: join(__dirname, 'src/Playground/PlaygroundRenderer.js'),
    PlaygroundErrorRenderer: join(__dirname, 'src/PlaygroundError/PlaygroundErrorRenderer.js'),
    ReactComponent: join(__dirname, 'src/ReactComponent'),
    ReactComponentRenderer: join(__dirname, 'src/ReactComponent/ReactComponentRenderer.js'),
    RibbonRenderer: join(__dirname, 'src/Ribbon/RibbonRenderer.js'),
    Section: join(__dirname, 'src/Section'),
    SectionRenderer: join(__dirname, 'src/Section/SectionRenderer.js'),
    SectionHeading: join(__dirname, 'src/SectionHeading'),
    SectionHeadingRenderer: join(__dirname, 'src/SectionHeading/SectionHeadingRenderer.js'),
    Sections: join(__dirname, 'src/Sections'),
    SectionsRenderer: join(__dirname, 'src/Sections/SectionsRenderer.js'),
    slots: join(__dirname, 'src/slots'),
    TabButtonRenderer: join(__dirname, 'src/TabButton/TabButtonRenderer.js'),
    TableRenderer: join(__dirname, 'src/Table/TableRenderer.js'),
    TableOfContents: join(__dirname, 'src/TableOfContents'),
    TableOfContentsRenderer: join(__dirname, 'src/TableOfContents/TableOfContentsRenderer.js'),
    TextRenderer: join(__dirname, 'src/Text/TextRenderer.js'),
    ToolbarButtonRenderer: join(__dirname, 'src/ToolbarButton/ToolbarButtonRenderer.js'),
    TypeRenderer: join(__dirname, 'src/Type/TypeRenderer.js'),
    Usage: join(__dirname, 'src/Usage/Usage.js'),
    VersionRenderer: join(__dirname, 'src/Version/VersionRenderer.js'),
    WelcomeRenderer: join(__dirname, 'src/Welcome/WelcomeRenderer.js'),
  },
});

module.exports = config;
