const path = require('path');
const { default: createConfig } = require('@yeutech-lab/rollup-umd-documentation/lib/styleguide.config');

module.exports = createConfig({
  styleguideComponents: {
    // components
    StyleGuideRenderer: path.join(__dirname, 'src/StyleGuide'),
    Wrapper: path.join(__dirname, 'src/Wrapper'),
    // rsg-bs-components
    ArgumentRenderer: path.join(__dirname, 'src/Argument/ArgumentRenderer.js'),
    ArgumentsRenderer: path.join(__dirname, 'src/Arguments/ArgumentsRenderer.js'),
    CodeRenderer: path.join(__dirname, 'src/Code/CodeRenderer.js'),
    ComponentsRenderer: path.join(__dirname, 'src/Components/ComponentsRenderer.js'),
    ComponentsList: path.join(__dirname, 'src/ComponentsList/ComponentsList.js'),
    ComponentsListRenderer: path.join(__dirname, 'src/ComponentsList/ComponentsListRenderer.js'),
    Editor: path.join(__dirname, 'src/Editor/Editor.js'),
    EditorLoaderRenderer: path.join(__dirname, 'src/Editor/EditorLoaderRenderer.js'),
    ErrorRenderer: path.join(__dirname, 'src/Error/ErrorRenderer.js'),
    ExamplePlaceholderRenderer: path.join(__dirname, 'src/ExamplePlaceholder/ExamplePlaceholderRenderer.js'),
    ExamplesRenderer: path.join(__dirname, 'src/Examples/ExamplesRenderer.js'),
    HeadingRenderer: path.join(__dirname, 'src/Heading/HeadingRenderer.js'),
    LinkRenderer: path.join(__dirname, 'src/Link/LinkRenderer.js'),
    LogoRenderer: path.join(__dirname, 'src/Logo/LogoRenderer.js'),
    Markdown: path.join(__dirname, 'src/Markdown'),
    Blockquote: path.join(__dirname, 'src/Markdown/Blockquote'),
    BlockquoteRenderer: path.join(__dirname, 'src/Markdown/Blockquote/BlockquoteRenderer.js'),
    Checkbox: path.join(__dirname, 'src/Markdown/Checkbox'),
    CheckboxRenderer: path.join(__dirname, 'src/Markdown/Checkbox/CheckboxRenderer.js'),
    Hr: path.join(__dirname, 'src/Markdown/Hr'),
    HrRenderer: path.join(__dirname, 'src/Markdown/Hr/HrRenderer.js'),
    JsDoc: path.join(__dirname, 'src/JsDoc'),
    List: path.join(__dirname, 'src/Markdown/List'),
    ListRenderer: path.join(__dirname, 'src/Markdown/List/ListRenderer.js'),
    MarkdownHeading: path.join(__dirname, 'src/Markdown/MarkdownHeading'),
    MarkdownHeadingRenderer: path.join(__dirname, 'src/Markdown/MarkdownHeading/MarkdownHeadingRenderer.js'),
    Pre: path.join(__dirname, 'src/Markdown/Pre'),
    PreRenderer: path.join(__dirname, 'src/Markdown/Pre/PreRenderer.js'),
    TableHeadRenderer: path.join(__dirname, 'src/Markdown/Table/TableHeadRenderer.js'),
    TableBodyRenderer: path.join(__dirname, 'src/Markdown/Table/TableBodyRenderer.js'),
    TableRowRenderer: path.join(__dirname, 'src/Markdown/Table/TableRowRenderer.js'),
    TableCellRenderer: path.join(__dirname, 'src/Markdown/Table/TableCellRenderer.js'),
    MessageRenderer: path.join(__dirname, 'src/Message/MessageRenderer.js'),
    MethodsRenderer: path.join(__dirname, 'src/Methods/MethodsRenderer.js'),
    NameRenderer: path.join(__dirname, 'src/Name/NameRenderer.js'),
    ParaRenderer: path.join(__dirname, 'src/Para/ParaRenderer.js'),
    PathlineRenderer: path.join(__dirname, 'src/Pathline/PathlineRenderer.js'),
    PlaygroundRenderer: path.join(__dirname, 'src/Playground/PlaygroundRenderer.js'),
    PlaygroundErrorRenderer: path.join(__dirname, 'src/PlaygroundError/PlaygroundErrorRenderer.js'),
    ReactComponentRenderer: path.join(__dirname, 'src/ReactComponent/ReactComponentRenderer.js'),
    RibbonRenderer: path.join(__dirname, 'src/Ribbon/RibbonRenderer.js'),
    SectionRenderer: path.join(__dirname, 'src/Section/SectionRenderer.js'),
    SectionHeadingRenderer: path.join(__dirname, 'src/SectionHeading/SectionHeadingRenderer.js'),
    SectionsRenderer: path.join(__dirname, 'src/Sections/SectionsRenderer.js'),
    slots: path.join(__dirname, 'src/slots'),
    TabButtonRenderer: path.join(__dirname, 'src/TabButton/TabButtonRenderer.js'),
    TableRenderer: path.join(__dirname, 'src/Table/TableRenderer.js'),
    TableOfContents: path.join(__dirname, 'src/TableOfContents/TableOfContents'),
    TableOfContentsRenderer: path.join(__dirname, 'src/TableOfContents/TableOfContentsRenderer.js'),
    TextRenderer: path.join(__dirname, 'src/Text/TextRenderer.js'),
    ToolbarButtonRenderer: path.join(__dirname, 'src/ToolbarButton/ToolbarButtonRenderer.js'),
    TypeRenderer: path.join(__dirname, 'src/Type/TypeRenderer.js'),
    Usage: path.join(__dirname, 'src/Usage/Usage.js'),
    VersionRenderer: path.join(__dirname, 'src/Version/VersionRenderer.js'),
    WelcomeRenderer: path.join(__dirname, 'src/Welcome/WelcomeRenderer.js'),
  },
});
